feat_hand_crafted: false
feat_random_cnn: false
rotation_net: false
flip_net: false
flip_net_ft: false
flip_net_mlp: false
harnet_ft: false
load_weights: false
load_personalized_weights: false
evaluation_name: BiGRU
input_size: 300
num_epoch: 50
num_workers: 6
learning_rate: 0.001
patience: 100
freeze_weight: false
mlp_net: false
use_early_stopping: true
flip_net_path: /data/ssl_wearable/model/2025-05-21_23:02:36tmp.pt #BiGRU model trained on REALWORLD_WISDM (5 classes) 50 epochs, lr=0.001

