## baselines
## Pre-trained flip-net fine-tuned the linear layers only and freeze all the features

feat_hand_crafted: false
feat_random_cnn: false

# trained networks
model_path: /data/UKBB/SSL/day_sec_10k/logs/models
flip_net: true
flip_net_ft: false
flip_net_random_mlp: false
harnet_ft: false
load_weights: true
freeze_weight: true
flip_net_path: /data/ssl_wearable/model/mtl_best.mdl
input_size: 300  # input size after resampling the raw data
subR: 1


# hyper-parameters
learning_rate: 0.0001
num_workers: 6
patience: 5
num_epoch: 200
evaluation_name: flip_net_rf_100k_freeze

