feat_hand_crafted: false
feat_random_cnn: false
rotation_net: false
flip_net: false
flip_net_ft: true
flip_net_mlp: false
harnet_ft: false
load_weights: true
load_personalized_weights: false
evaluation_name: transformer
input_size: 300
num_epoch: 50
num_workers: 6
learning_rate: 0.001
patience: 100
freeze_weight: false
mlp_net: false
use_early_stopping: true
# flip_net_path: /data/ssl_wearable/model/2025-04-15_00:30:31tmp.pt #Transformer model trained on REALWORLD_WISDM (5 classes) 50 epochs, lr=0.001, 4 head
flip_net_path: /data/ssl_wearable/model/2025-05-20_15:52:29tmp.pt #Transformer model trained on REALWORLD_WISDM (5 classes) 50 epochs, lr=0.001, 8 head
# flip_net_path: /data/ssl_wearable/model/2025-05-20_16:43:48tmp.pt #Transformer model trained on REALWORLD_WISDM then fine tuned on MyMove LOSO (5 classes) 50 epochs, lr=0.001, 8 head
# flip_net_path: /data/ssl_wearable/model/2025-05-21_01:35:37tmp.pt #Transformer model trained on MyMove LOSO (5 classes) 50 epochs, lr=0.001, 8 head