defaults:
  - _self_
  - data: wisdm_10s_few_class
  - evaluation: all
  - model: resnet
  - dataloader: ten_sec
  - evaluation_data: mymove_10s
  - cross_dataset_mapping: mymove_wisdm

cross_dataset: false
use_pretrained: true
gpu: -1
gpu_ids: [0, 1, 2]  # gpus to use if multi_gpu==true
multi_gpu: true
num_split: 5
augmentation: true
model_path: /home/hossein/ssl-wearables/2025-02-18_19:32:24tmp.pt
logging_path: /data/UKBB/SSL/evaluations
report_root: "~/ssl-wearables/data/reports/"
# report_path: "${report_root}${data.dataset_name}_${evaluation.evaluation_name}_${data.subject_count}.csv"
report_path: "${report_root}${data.dataset_name}_${evaluation.evaluation_name}_${data.subject_count}_${evaluation.subR}.csv"
is_verbose: false
