defaults:
  - _self_
  - data: mymove_10s_5c
  - evaluation: all
  - model: resnet
  - dataloader: ten_sec

#experiment modes
cross_dataset: false #set it true when you want to start training on one dataset and evaluate on another dataset
use_pretrained: false #set it to true when you want to use a pretrained model (either on the same dataset or another dataset)
split_method: "sequential" # "k_shot" or "sequential" or "held_one_subject_out" or "random_kfold"
k_shot: 10 # number of shots for k-shot learning
train_ratio: 0.6 # ratio of training data in sequential split
num_split: 5 # number of splits for random kfold split
augmentation: true

gpu: -1
gpu_ids: [0, 1, 2, 4]  # gpus to use if multi_gpu==true
multi_gpu: true


logging_path: /data/UKBB/SSL/evaluations
report_root: "~/ssl-wearables/data/reports/"
mapping_path: "conf/cross_dataset_mapping/Activity_label_mapping.json"
# trained_label_mapping_path: "${report_root}2025-03-08_05-22/label_mapping.json" #ExtraSensory
trained_label_mapping_path: "${report_root}2025-02-18_19-32/label_mapping.json" #WISDM (4 classes)
# model path to be used only if use_pretrained is set to true
# model_path: /home/hossein/ssl-wearables/2025-03-08_05:22:16tmp.pt # trained on Extra Sensory
model_path: /home/hossein/ssl-wearables/2025-02-18_19:32:24tmp.pt # trained on WISDM (4 classes)
# report_path: "${report_root}${data.dataset_name}_${evaluation.evaluation_name}_${data.subject_count}.csv"
report_path: "${report_root}${data.dataset_name}_${evaluation.evaluation_name}_${data.subject_count}_${evaluation.subR}.csv"
is_verbose: false
