defaults:
  - _self_
  - data: mymove_10s_5c_v2
  - evaluation: mlp_ft
  - model: mlp
  - dataloader: ten_sec

#experiment modes
cross_dataset: false #set it true when you want to start training on one dataset and evaluate on another dataset
use_pretrained: false #set it to true when you want to use a pretrained model (either on the same dataset or another dataset)
split_method: "held_one_subject_out" # "k_shot" or "sequential" or "held_one_subject_out" or "random_kfold" or "k_shot_fixed" or "held_one_subject_out_k_shot"
k_shot: 50 # number of shots for k-shot learning
train_ratio: 0.6 # ratio of training data in sequential split
num_split: 5 # number of splits for random kfold split
augmentation: false

gpu: -1
gpu_ids: [0, 1, 2, 4]  # gpus to use if multi_gpu==true
multi_gpu: true


logging_path: /data/ssl_wearable/logs
report_root: "~/ssl-wearables/data/reports/"
mapping_path: "conf/cross_dataset_mapping/Activity_label_mapping v2 5c.json"
# trained_label_mapping_path: "${report_root}2025-03-08_05-22/label_mapping.json" #ExtraSensory
trained_label_mapping_path: "${report_root}2025-04-08_14-42/label_mapping.json" #realworld_wisdm (5 classes) - fine tuned on MyMove LOSO
# model path to be used only if use_pretrained is set to true
model_path: ""
# model_path: /home/hossein/ssl-wearables/2025-03-08_05:22:16tmp.pt # trained on Extra Sensory
# model_path: /home/hossein/ssl-wearables/2025-02-18_19:32:24tmp.pt # trained on WISDM (4 classes)
# model_path: /home/hossein/ssl-wearables/2025-04-08_10:30:51tmp.pt # trained on realworld_wisdm (frozen representation) (5 classes)
# model_path: /home/hossein/ssl-wearables/2025-04-08_14:42:33tmp.pt # trained on realworld_wisdm (frozen representation) (5 classes) fine tuned on MyMove LOSO
# report_path: "${report_root}${data.dataset_name}_${evaluation.evaluation_name}_${data.subject_count}.csv"
report_path: "${report_root}${data.dataset_name}_${evaluation.evaluation_name}_${data.subject_count}.csv"
is_verbose: false
