learning_rate: 0.0001
name: "resnet_transformer_lr${model.learning_rate}\
       _resnet_v${model.resnet_version}_win_size${dataloader.epoch_len}_sample${dataloader.num_sample_per_subject}"
mixed_precision: false
resnet_version: 1
warm_up_step: 5
lr_scale: true
patience: 5
is_ae: false
