# 14 subjects
# Preprocessing done:
# 1. Remove subject 2
data_root: /data/ssl_wearable/data/downstream/realworld_30hz_few_class
X_path: "${evaluation_data.data_root}/X.npy"
Y_path:  "${evaluation_data.data_root}/Y.npy"
PID_path:  "${evaluation_data.data_root}/pid.npy"
sample_rate: 30
task_type: 'classify'
output_size: 5
batch_size: 500
held_one_subject_out: false
weighted_loss_fn: true
dataset_name: 'realworld'
subject_count: -1
ratio2keep: 1
